V1.1.0 - ready (#25)
* V1.0.5 BETA (#15)

* :sparkles: v1.0.5 - Try It Out
* Removed the bridge to the titles and cleaned so of the code

* feat: :test_tube: Better CI/CD to include the pre-release branch

Invalid version on purpose to test the version validation

Invalid version on purpose to test the version validation

* run version check on pre-release PR

* Now with valid version

* beta v2 (#16)

* V1.0.5   try it out (#17)

* feat: :sparkles: v1.0.5 - Try It Out

Added a box to try out the service directly in the home page

* v1.0.5 - BETA

* beta 1

* removed the bridge to the titles and cleaned so of the code

* feat: :test_tube: Better CI/CD to include the pre-release branch

Invalid version on purpose to test the version validation

Invalid version on purpose to test the version validation

* run version check on pre-release PR

* Now with valid version

* beta v2 fixed homepage tags

* fix: :bug: Fixed wrong endpoint for SEO

* :sparkles: Refactoring of the homepage to use libraries (#18)

* :sparkles: Allow Multple connection with same token + cleaned bit the Home Page

* fixed beta version number (#21)

* style: :art: cleaned up the HomePage (#22)

* v1.1.0 RC1- Ready | Uniformed the theme (#23)

* 1.1.0 - RC2 (#24)

* ci: Check the diff of the changes.md

* ci: Fixed the if statements to check the version depending on the target of the PR

* v1.1.0 - READY

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,13 +2,71 @@ name: CI/CD
 
 on:
   push:
-    branches: [ master ]
+    branches: [ master, pre-release ]
   pull_request:
-    branches: [ master ]
+    branches: [ master, pre-release ]
 
 jobs:
+  get-version:
+    name: Get versions (main-stage-devVersion)
+    runs-on: ubuntu-latest
+
+    outputs:
+      versionMain: ${{ steps.get_version.outputs.versionMain }}
+      versionDevStage: ${{ steps.get_version.outputs.versionDevStage }}
+      versionDevVersion: ${{ steps.get_version.outputs.versionDevVersion }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Get version
+        id: get_version
+        run: |
+          versionMain=$(grep -oP "version=\"\K[0-9.]+" app/main.py || echo "NO_MAIN_VERSION")
+          versionDevStage=$(grep -oP 'version=\"\K[0-9.]+-\K[a-zA-Z]+' app/main.py || echo "NO_DEV_STAGE")
+          versionDevVersion=$(grep -oP 'version=\"\K[0-9.]+-\K[a-zA-Z]+-\K[a-zA-Z0-9.]+' app/main.py || echo "NO_DEV_VERSION")
+          echo "versionMain=$versionMain" >> $GITHUB_OUTPUT
+          echo "versionDevStage=$versionDevStage" >> $GITHUB_OUTPUT
+          echo "versionDevVersion=$versionDevVersion" >> $GITHUB_OUTPUT
+
+      - name: Check Main Version
+        run: |
+          if [ "${{ steps.get_version.outputs.versionMain }}" == "NO_MAIN_VERSION" ]; then
+            echo "Fail: invalid main version (missing)"
+            exit 1
+          fi
+
+      - name: Check Version for Production
+        if: github.event.pull_request.base.ref == 'master'
+        run: |
+          changelogVersion=$(grep "\[${{ steps.get_version.outputs.versionMain }}\]" CHANGES.md || echo "NO_VERSION")
+          if [ "$changelogVersion" == "NO_VERSION" ]; then
+            echo "Version ${{ steps.get_version.outputs.versionMain }} not found in changelog"
+            exit 1
+          fi
+          if [ "${{ steps.get_version.outputs.versionDevStage }}" != "NO_DEV_STAGE" ]; then
+            echo "No development stage allowed in production"
+            exit 1
+          fi
+          if [ "${{ steps.get_version.outputs.versionDevVersion }}" != "NO_DEV_VERSION" ]; then
+            echo "No development version allowed in production"
+            exit 1
+          fi
+
+      - name: Check Dev Stage
+        if: github.event.pull_request.base.ref == 'pre-release'
+        run: |
+          if [ "${{ steps.get_version.outputs.versionDevStage }}" == "NO_DEV_STAGE" ]; then
+            echo "Fail: invalid development stage (missing)"
+            exit 1
+          fi
+
   test:
     name: Run tests and collect coverage and linting
+    needs: get-version
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -42,20 +100,14 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
 
   deploy:
-    needs: test
-    if: github.ref == 'refs/heads/master'
+    needs: [get-version, test]
+    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/pre-release'
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
-
-    - name: Get version
-      id: get_version
-      run: |
-        version=$(grep -oP "version=\"\K[0-9.]+" app/main.py || echo "0.0.0")
-        echo "version=$version" >> $GITHUB_OUTPUT
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -69,10 +121,32 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN  }}
 
-    - name: Build and push Docker images
+    - name: Build and push Docker images (master)
+      if: github.ref == 'refs/heads/master' && needs.get-version.outputs.versionDevStage == 'NO_DEV_STAGE' && needs.get-version.outputs.versionDevVersion == 'NO_DEV_VERSION'
       uses: docker/build-push-action@v6
       with:
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:latest
-          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ steps.get_version.outputs.version }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ needs.get-version.outputs.versionMain }}
+
+    - name: Build and push Docker images (pre-release with subversion)
+      if: github.ref == 'refs/heads/pre-release' && needs.get-version.outputs.versionDevStage != 'NO_DEV_STAGE' && needs.get-version.outputs.versionDevVersion != 'NO_DEV_VERSION'
+      uses: docker/build-push-action@v6
+      with:
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-${{ needs.get-version.outputs.versionMain }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-${{ needs.get-version.outputs.versionMain }}-${{ needs.get-version.outputs.versionDevStage }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-${{ needs.get-version.outputs.versionMain }}-${{ needs.get-version.outputs.versionDevStage }}-${{ needs.get-version.outputs.versionDevVersion }}
+
+    - name: Build and push Docker images (pre-release without subversion)
+      if: github.ref == 'refs/heads/pre-release' && needs.get-version.outputs.versionDevStage != 'NO_DEV_STAGE' && needs.get-version.outputs.versionDevVersion == 'NO_DEV_VERSION'
+      uses: docker/build-push-action@v6
+      with:
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-${{ needs.get-version.outputs.versionMain }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-${{ needs.get-version.outputs.versionMain }}-${{ needs.get-version.outputs.versionDevStage }}
