feat: :test_tube: Better CI/CD to include the pre-release branch
Invalid version on purpose to test the version validation

Invalid version on purpose to test the version validation

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -2,9 +2,9 @@ name: CI/CD
 
 on:
   push:
-    branches: [ master ]
+    branches: [ master, pre-release ]
   pull_request:
-    branches: [ master ]
+    branches: [ master, pre-release ]
 
 jobs:
   test:
@@ -15,6 +15,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
+      - name: Check version for pre-release
+        if: github.ref == 'refs/heads/pre-release'
+        run: |
+          validState=$(grep -oP 'version=\"\K[0-9.]+-\K['-']+' app/main.py || echo "valid")
+          if [ "$validState" != "valid" ]; then
+            echo "Fail: invalid development state (missing)"
+            exit 1
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -43,7 +52,7 @@ jobs:
 
   deploy:
     needs: test
-    if: github.ref == 'refs/heads/master'
+    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/pre-release'
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
@@ -55,7 +64,11 @@ jobs:
       id: get_version
       run: |
         version=$(grep -oP "version=\"\K[0-9.]+" app/main.py || echo "0.0.0")
+        versionState=$(grep -oP 'version=\"\K[0-9.]+-\K[a-zA-Z]+' app/main.py || echo "dev")
+        versionSub=$(grep -oP 'version=\"\K[0-9.]+-\K[a-zA-Z]+-\K[a-zA-Z0-9.]+' app/main.py || echo "missing")
         echo "version=$version" >> $GITHUB_OUTPUT
+        echo "versionState=$versionState" >> $GITHUB_OUTPUT
+        echo "versionSub=$versionSub" >> $GITHUB_OUTPUT
 
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -69,10 +82,33 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN  }}
 
-    - name: Build and push Docker images
+    - name: Build and push Docker images (master)
+      if: github.ref == 'refs/heads/master'
       uses: docker/build-push-action@v6
       with:
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:latest
           ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ steps.get_version.outputs.version }}
+
+    - name: Build and push Docker images (pre-release with subversion)
+      if: github.ref == 'refs/heads/pre-release' && steps.get_version.outputs.versionSub != 'missing'
+      uses: docker/build-push-action@v6
+      with:
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-latest
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:latest-${{ steps.get_version.outputs.versionState }}-latest
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:latest-${{ steps.get_version.outputs.versionState }}-${{ steps.get_version.outputs.versionSub }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ steps.get_version.outputs.version }}-${{ steps.get_version.outputs.versionState }}-latest
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ steps.get_version.outputs.version }}-${{ steps.get_version.outputs.versionState }}-${{ steps.get_version.outputs.versionSub }}
+
+    - name: Build and push Docker images (pre-release without subversion)
+      if: github.ref == 'refs/heads/pre-release' && steps.get_version.outputs.versionSub == 'missing'
+      uses: docker/build-push-action@v6
+      with:
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:dev-latest
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:latest-${{ steps.get_version.outputs.versionState }}
+          ${{ secrets.DOCKER_USERNAME }}/kofi-websocket:${{ steps.get_version.outputs.version }}-${{ steps.get_version.outputs.versionState }}
